# Generated by Django 3.2 on 2022-01-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('type_of_event', models.CharField(choices=[('private party', 'PRIVATE PARTY'), ('birthday party', 'BIRTHDAY PARTY'), ('Diner and movie', 'DINER AND MOVIE')], max_length=50)),
                ('number_of_persons', models.IntegerField()),
                ('Date_of_event', models.DateField()),
                ('message', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='event/')),
            ],
            options={
                'verbose_name': 'events',
                'verbose_name_plural': 'events',
            },
        ),
    ]
