# Generated by Django 3.2 on 2022-01-19 10:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_events_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='feautured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
