# Generated by Django 3.2 on 2022-01-19 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_events_feautured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='feautured_image',
        ),
    ]
