# Generated by Django 3.2 on 2022-01-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_events_feautured_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='event/')),
            ],
            options={
                'verbose_name': 'event_image',
                'verbose_name_plural': 'event_image',
            },
        ),
    ]
