# Generated by Django 3.2 on 2022-01-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_remove_menu_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='list/')),
            ],
            options={
                'verbose_name': 'specials',
                'verbose_name_plural': 'specials',
            },
        ),
    ]
