# Generated by Django 3.2 on 2022-01-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_specials'),
    ]

    operations = [
        migrations.AddField(
            model_name='specials',
            name='description',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='specials',
            name='specialty',
            field=models.CharField(default='', max_length=50),
        ),
    ]
